# Cloudflare Pages project config
name = "xpromo-v2"
compatibility_date = "2024-02-05"

# Đây là folder output cho website (public)
pages_build_output_dir = "public"

[build]
command = ""

[dev]
ip = "0.0.0.0"
port = 8787

# Bật npm modules cho Pages Functions
[experimental]
enable_pages_builds = true
